#!/usr/bin/env bash
# Generate bootstrap/cli/embed.glide with byte arrays of the inputs baked in.
#
# Run in the release pipeline just before building the bundle binary. The
# resulting compiler links every supplied sysroot + the src/ tree
# straight into .rodata, so a single-file install can build for any
# supported target with zero network access.
#
# Usage:
#   tools/gen_embedded_blobs.sh \
#       --src=dist/src-0.3.1.tar.gz \
#       --sysroot=dist/glide-sysroot-x86_64-linux-musl-0.3.1.tar.gz \
#       --sysroot=dist/glide-sysroot-aarch64-linux-musl-0.3.1.tar.gz \
#       ...
#
# Idempotent: regenerating with the same inputs produces byte-for-byte
# the same embed.glide. Restore the default (no-embed) version with
# `git checkout -- bootstrap/cli/embed.glide`.

set -e

SRC_TARBALL=""
SYSROOTS=()
OUT="bootstrap/cli/embed.glide"

while [ $# -gt 0 ]; do
    case "$1" in
        --src=*)     SRC_TARBALL="${1#--src=}"; shift ;;
        --sysroot=*) SYSROOTS+=("${1#--sysroot=}"); shift ;;
        --out=*)     OUT="${1#--out=}"; shift ;;
        *)           echo "unknown arg: $1" >&2; exit 1 ;;
    esac
done

if ! command -v od >/dev/null 2>&1; then
    echo "gen_embedded_blobs: od is required (coreutils)." >&2
    exit 1
fi

triple_from_tarball() {
    # dist/glide-sysroot-x86_64-linux-musl-0.3.1.tar.gz -> x86_64-linux-musl
    local base
    base="$(basename "$1")"
    base="${base#glide-sysroot-}"
    # Strip the trailing -<version>.tar.gz. Version is anything after the
    # last `-` before `.tar.gz`.
    base="${base%.tar.gz}"
    base="${base%-*}"
    echo "$base"
}

# Convert input file to a `static const unsigned char NAME[] = { ... };`
# + `static const unsigned int NAME_len = N;` pair. Uses od + awk
# instead of `xxd -i` so it runs on every platform's default toolset
# (xxd isn't a standalone MSYS2/pacman package). `od -An -v -tx1`
# streams space-separated hex bytes; awk packs them into C with line
# wrapping, and `wc -c` gives the exact length.
emit_array() {
    local symbol="$1" path="$2"
    local n
    n=$(wc -c < "$path" | tr -d ' ')
    # Emit the bytes as a C string literal ("\xNN\xNN"...) rather than a
    # {0x..,..} array. clang/gcc build a per-element AST node for an array
    # initializer, so a ~100 MB embedded blob costs many GB of compiler RAM and
    # OOMs the release runners; a string literal is parsed as one opaque blob.
    # Each byte is \xNN (two hex digits) so the next \x always delimits the
    # previous escape - no ambiguity from a trailing hex digit. The implicit NUL
    # terminator + any embedded NULs are harmless: readers use ${symbol}_len.
    echo "static const unsigned char ${symbol}[] ="
    od -An -v -tx1 "$path" | awk '
        BEGIN { bs = "\\" }
        {
            printf "\""
            for (i = 1; i <= NF; i++) printf "%sx%s", bs, $i
            printf "\"\n"
        }
    '
    echo ";"
    echo "static const unsigned int ${symbol}_len = ${n};"
}

mkdir -p "$(dirname "$OUT")"

{
    cat <<'HEADER'
// AUTO-GENERATED by tools/gen_embedded_blobs.sh for a bundle release
// build. Do not edit by hand — restore the no-embed default with:
//   git checkout -- bootstrap/cli/embed.glide
//
// This file is the same shape as the checked-in default; the only
// difference is the c_raw block, which here ships real byte arrays
// for every embedded sysroot + the src/ tree and points the
// dispatch fns at them.

c_raw! {
    #include <stddef.h>
    #include <string.h>

HEADER

    if [ -n "$SRC_TARBALL" ]; then
        echo "    // Glide src/ tree ($(du -h "$SRC_TARBALL" | cut -f1))."
        emit_array "EMBED_SRC_DATA" "$SRC_TARBALL" | sed 's/^/    /'
        echo ""
        echo "    static void* __glide_embed_src(void) { return (void*)EMBED_SRC_DATA; }"
        echo "    static int   __glide_embed_src_len(void) { return (int)EMBED_SRC_DATA_len; }"
    else
        echo "    static void* __glide_embed_src(void) { return (void*)0; }"
        echo "    static int   __glide_embed_src_len(void) { return 0; }"
    fi
    echo ""

    # Per-sysroot arrays.
    for tb in "${SYSROOTS[@]}"; do
        triple="$(triple_from_tarball "$tb")"
        sym="EMBED_SR_$(echo "$triple" | tr 'a-z-' 'A-Z_')"
        echo "    // Sysroot $triple ($(du -h "$tb" | cut -f1))."
        emit_array "${sym}_DATA" "$tb" | sed 's/^/    /'
        echo ""
    done

    # strcmp dispatch.
    echo "    static void* __glide_embed_sysroot(const char* triple) {"
    for tb in "${SYSROOTS[@]}"; do
        triple="$(triple_from_tarball "$tb")"
        sym="EMBED_SR_$(echo "$triple" | tr 'a-z-' 'A-Z_')"
        echo "        if (strcmp(triple, \"${triple}\") == 0) return (void*)${sym}_DATA;"
    done
    echo "        return (void*)0;"
    echo "    }"
    echo "    static int __glide_embed_sysroot_len(const char* triple) {"
    for tb in "${SYSROOTS[@]}"; do
        triple="$(triple_from_tarball "$tb")"
        sym="EMBED_SR_$(echo "$triple" | tr 'a-z-' 'A-Z_')"
        echo "        if (strcmp(triple, \"${triple}\") == 0) return (int)${sym}_DATA_len;"
    done
    echo "        return 0;"
    echo "    }"

    cat <<'FOOTER'
}

extern fn __glide_embed_sysroot(triple: string) -> *void;
extern fn __glide_embed_sysroot_len(triple: string) -> i32;
extern fn __glide_embed_src() -> *void;
extern fn __glide_embed_src_len() -> i32;

/// Pointer to the embedded sysroot tarball for `triple`, or null when
/// it isn't bundled in this build.
pub fn embedded_sysroot(triple: string) -> *void { return __glide_embed_sysroot(triple); }

/// Size in bytes of the embedded sysroot for `triple`, or 0 when
/// it isn't bundled.
pub fn embedded_sysroot_len(triple: string) -> i32 { return __glide_embed_sysroot_len(triple); }

/// Pointer to the embedded `src/` tree tarball, or null on
/// non-bundle builds.
pub fn embedded_src() -> *void { return __glide_embed_src(); }

/// Size in bytes of the embedded `src/` tarball, or 0 on non-bundle builds.
pub fn embedded_src_len() -> i32 { return __glide_embed_src_len(); }

/// True when this glide binary ships an embedded sysroot for `triple`.
pub fn has_embedded_sysroot(triple: string) -> bool { return __glide_embed_sysroot_len(triple) > 0; }

/// True when this glide binary ships an embedded `src/` tree.
pub fn has_embedded_src() -> bool { return __glide_embed_src_len() > 0; }
FOOTER
} > "$OUT"

echo ">> Wrote $OUT"
echo ""
echo "Bundle inputs:"
[ -n "$SRC_TARBALL" ] && echo "  src:       $SRC_TARBALL ($(du -h "$SRC_TARBALL" | cut -f1))"
for tb in "${SYSROOTS[@]}"; do
    echo "  sysroot:   $(triple_from_tarball "$tb") ($(du -h "$tb" | cut -f1))"
done
echo ""
echo "Embedded total:  $(du -h "$OUT" | cut -f1)  (compile will inline)"
